[functions]
directory = "netlify/functions"

[[redirects]]
  from = "/substack"
  to = "/.netlify/functions/fetchArticles"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
